{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cosmos.fullname" . }}-data
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
  annotations:
    # Retain PVC even after release deletion to prevent data loss
    helm.sh/resource-policy: keep
    # Enable encryption at rest for data security
    encryption.cosmos.ai/enabled: "true"
    {{- if .Values.persistence.annotations }}
    {{- toYaml .Values.persistence.annotations | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany  # Enable distributed access for ML workloads
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "100Gi" }}
---
{{- if .Values.models.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cosmos.fullname" . }}-models
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    encryption.cosmos.ai/enabled: "true"
    {{- if .Values.models.persistence.annotations }}
    {{- toYaml .Values.models.persistence.annotations | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.models.persistence.storageClass }}
  storageClassName: {{ .Values.models.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.models.persistence.size | default "500Gi" }}
---
{{- end }}
{{- if .Values.cache.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cosmos.fullname" . }}-cache
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    encryption.cosmos.ai/enabled: "true"
    {{- if .Values.cache.persistence.annotations }}
    {{- toYaml .Values.cache.persistence.annotations | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.cache.persistence.storageClass }}
  storageClassName: {{ .Values.cache.persistence.storageClass }}
  {{- else if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.cache.persistence.size | default "200Gi" }}
{{- end }}
{{- end }}