{{/* Generate Kubernetes Secrets for Cosmos WFM Platform */}}

{{/* Backend Service Secrets */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmos.fullname" . }}-backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
  annotations:
    # Secret rotation policy
    secret.cosmos.ai/rotation-schedule: "720h" # 30 days
    secret.cosmos.ai/last-rotated: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }}
    # Checksum for updates
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # External secret store integration
    vault.hashicorp.com/role: "cosmos-backend"
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Database credentials
  {{- if .Values.backend.database }}
  DB_HOST: {{ .Values.backend.database.host | b64enc | quote }}
  DB_PORT: {{ .Values.backend.database.port | toString | b64enc | quote }}
  DB_NAME: {{ .Values.backend.database.name | b64enc | quote }}
  DB_USER: {{ .Values.backend.database.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.backend.database.password | b64enc | quote }}
  {{- end }}

  # Cloud provider credentials
  {{- if .Values.backend.cloud }}
  AWS_ACCESS_KEY_ID: {{ .Values.backend.cloud.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.backend.cloud.aws.secretAccessKey | b64enc | quote }}
  GCP_SERVICE_ACCOUNT_KEY: {{ .Values.backend.cloud.gcp.serviceAccountKey | b64enc | quote }}
  AZURE_CLIENT_ID: {{ .Values.backend.cloud.azure.clientId | b64enc | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.backend.cloud.azure.clientSecret | b64enc | quote }}
  {{- end }}

  # JWT configuration
  {{- if .Values.backend.jwt }}
  JWT_SECRET_KEY: {{ .Values.backend.jwt.secretKey | b64enc | quote }}
  JWT_PUBLIC_KEY: {{ .Values.backend.jwt.publicKey | b64enc | quote }}
  JWT_EXPIRY: {{ .Values.backend.jwt.expiry | default "24h" | b64enc | quote }}
  {{- end }}

  # API keys and tokens
  {{- if .Values.backend.api }}
  API_KEY: {{ .Values.backend.api.key | b64enc | quote }}
  API_SECRET: {{ .Values.backend.api.secret | b64enc | quote }}
  {{- end }}

---
{{/* Web Interface Secrets */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmos.fullname" . }}-web-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
  annotations:
    # Secret rotation policy
    secret.cosmos.ai/rotation-schedule: "720h" # 30 days
    secret.cosmos.ai/last-rotated: {{ now | date "2006-01-02T15:04:05Z07:00" | quote }}
    # Checksum for updates
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    # External secret store integration
    vault.hashicorp.com/role: "cosmos-web"
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Authentication configuration
  {{- if .Values.web.auth }}
  AUTH_SECRET: {{ .Values.web.auth.secret | b64enc | quote }}
  SESSION_KEY: {{ .Values.web.auth.sessionKey | b64enc | quote }}
  COOKIE_SECRET: {{ .Values.web.auth.cookieSecret | b64enc | quote }}
  {{- end }}

  # API configuration
  {{- if .Values.web.api }}
  BACKEND_API_KEY: {{ .Values.web.api.key | b64enc | quote }}
  BACKEND_API_URL: {{ .Values.web.api.url | b64enc | quote }}
  {{- end }}

  # OAuth configuration
  {{- if .Values.web.oauth }}
  OAUTH_CLIENT_ID: {{ .Values.web.oauth.clientId | b64enc | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.web.oauth.clientSecret | b64enc | quote }}
  OAUTH_CALLBACK_URL: {{ .Values.web.oauth.callbackUrl | b64enc | quote }}
  {{- end }}

  # Analytics and monitoring
  {{- if .Values.web.analytics }}
  ANALYTICS_KEY: {{ .Values.web.analytics.key | b64enc | quote }}
  MONITORING_TOKEN: {{ .Values.web.analytics.monitoringToken | b64enc | quote }}
  {{- end }}