{{- if .Values.serviceAccount.create }}
---
# Backend Service Account for GPU workloads and API services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosmos.fullname" . }}-backend-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.serviceAccount.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

---
# Web Frontend Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosmos.fullname" . }}-web-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.serviceAccount.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true

---
# Monitoring Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosmos.fullname" . }}-monitoring-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  {{- with .Values.serviceAccount.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceAccount.monitoring.cloudProvider }}
  {{- if eq .Values.serviceAccount.monitoring.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.monitoring.iamRole }}
  {{- else if eq .Values.serviceAccount.monitoring.cloudProvider "gcp" }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.monitoring.iamRole }}
  {{- else if eq .Values.serviceAccount.monitoring.cloudProvider "azure" }}
    azure.workload.identity/client-id: {{ .Values.serviceAccount.monitoring.iamRole }}
  {{- end }}
  {{- end }}
automountServiceAccountToken: true

{{- if .Values.serviceAccount.extraServiceAccounts }}
{{- range .Values.serviceAccount.extraServiceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cosmos.fullname" $ }}-{{ .name }}-sa
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cosmos.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .component }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .automountToken | default true }}
{{- end }}
{{- end }}

{{- end }}