apiVersion: v1
kind: Secret
metadata:
  name: cosmos-backend-secrets
  namespace: cosmos
  labels:
    app: cosmos-backend
    component: secrets
    managed-by: manual
    encryption: aes256
  annotations:
    rotation-schedule: "90d"
    last-rotated: "2024-01-01T00:00:00Z"
    encryption-key: "kms://cosmos/backend/secrets"
type: Opaque
data:
  # Database Credentials
  DB_USERNAME: YWRtaW4K  # base64 encoded 'admin'
  DB_PASSWORD: Y2hhbmdlbWUK  # base64 encoded 'changeme'
  DB_NAME: Y29zbW9zX3Byb2QK  # base64 encoded 'cosmos_prod'

  # AWS Cloud Storage Credentials
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZPRE5ON0VYQU1QTEVL  # base64 encoded placeholder
  AWS_SECRET_ACCESS_KEY: d0phbGJHWXR2L2JFWEFNUExFS0VZL2JQeFJmaUNZRVhBTVBMRUtFWQo=  # base64 encoded placeholder

  # GCP Cloud Storage Credentials
  GCP_SERVICE_ACCOUNT_KEY: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY29zbW9zLXdmbSIsCiAgInByaXZhdGVfa2V5X2lkIjogImV4YW1wbGUiCn0K  # base64 encoded placeholder JSON

  # Azure Cloud Storage Credentials
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWV4YW1wbGU7QWNjb3VudEtleT1leGFtcGxlOw==  # base64 encoded placeholder

  # JWT Authentication
  JWT_SECRET: c3VwZXJzZWNyZXRrZXkxMjM0NTY3ODkK  # base64 encoded placeholder
  JWT_EXPIRY: MjRoCg==  # base64 encoded '24h'