apiVersion: v2
name: cosmos
description: Cosmos World Foundation Model Platform for synthetic data generation with GPU acceleration, monitoring, and security controls
type: application
version: 1.0.0
appVersion: 1.0.0

keywords:
  - ai
  - machine-learning
  - video-generation
  - gpu-computing
  - synthetic-data
  - world-foundation-model

maintainers:
  - name: Cosmos Team
    email: team@cosmos.ai

dependencies:
  # Prometheus for monitoring and metrics collection
  # prometheus-community/prometheus v15.0.0
  - name: prometheus
    version: 15.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
    tags:
      - monitoring

  # Grafana for metrics visualization and dashboards
  # grafana/grafana v6.0.0
  - name: grafana
    version: 6.0.0
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
    tags:
      - monitoring

  # NVIDIA GPU Operator for GPU resource management
  # nvidia/gpu-operator v2.0.0
  - name: gpu-operator
    version: 2.0.0
    repository: https://nvidia.github.io/gpu-operator
    condition: backend.gpu.enabled
    tags:
      - gpu