# kubernetes v1.24+
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmos-backend-sa
  namespace: cosmos-backend
  labels:
    app.kubernetes.io/name: cosmos-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cosmos-wfm
    security.cosmos.ai/reviewed: "true"
    security.cosmos.ai/last-audit: "2024-01-15"
  annotations:
    description: "Service account for backend API services and GPU workloads"
    owner: "platform-team@cosmos.ai"
    security.cosmos.ai/rotation-schedule: "90d"
    security.cosmos.ai/access-level: "restricted"
    security.cosmos.ai/audit-logging: "enabled"
automountServiceAccountToken: true
secrets:
  - name: cosmos-backend-token
    type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmos-web-sa
  namespace: cosmos-web
  labels:
    app.kubernetes.io/name: cosmos-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: cosmos-wfm
    security.cosmos.ai/reviewed: "true"
    security.cosmos.ai/last-audit: "2024-01-15"
  annotations:
    description: "Service account for web frontend components"
    owner: "frontend-team@cosmos.ai"
    security.cosmos.ai/rotation-schedule: "90d"
    security.cosmos.ai/access-level: "readonly"
    security.cosmos.ai/audit-logging: "enabled"
automountServiceAccountToken: true
secrets:
  - name: cosmos-web-token
    type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmos-monitoring-sa
  namespace: cosmos-monitoring
  labels:
    app.kubernetes.io/name: cosmos-monitoring
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: cosmos-wfm
    security.cosmos.ai/reviewed: "true"
    security.cosmos.ai/last-audit: "2024-01-15"
  annotations:
    description: "Service account for monitoring and metrics collection"
    owner: "sre-team@cosmos.ai"
    security.cosmos.ai/rotation-schedule: "90d"
    security.cosmos.ai/access-level: "monitoring"
    security.cosmos.ai/audit-logging: "enabled"
automountServiceAccountToken: true
secrets:
  - name: cosmos-monitoring-token
    type: kubernetes.io/service-account-token