# Kubernetes ConfigMap for Cosmos WFM Platform Web Interface
# Version: v1
# Purpose: Defines non-sensitive configuration settings for web interface containers

apiVersion: v1
kind: ConfigMap
metadata:
  name: cosmos-web-config
  namespace: cosmos
  labels:
    app.kubernetes.io/name: cosmos-web
    app.kubernetes.io/part-of: cosmos-platform
    app.kubernetes.io/component: frontend
data:
  # API Configuration
  VITE_API_BASE_URL: "/api/v1"
  VITE_API_TIMEOUT: "60000"  # API request timeout in milliseconds
  VITE_MAX_RETRIES: "3"      # Maximum number of API request retries
  VITE_RETRY_DELAY: "1000"   # Delay between retries in milliseconds

  # Feature Flags
  VITE_ENABLE_SAFETY_GUARDRAILS: "true"  # Enable safety guardrail features
  VITE_ENABLE_GPU_METRICS: "true"        # Enable GPU utilization metrics
  VITE_ENABLE_MODEL_METRICS: "true"      # Enable model performance metrics