apiVersion: v1
kind: Secret
metadata:
  name: cosmos-web-secrets
  namespace: cosmos
  labels:
    app.kubernetes.io/name: cosmos-web
    app.kubernetes.io/part-of: cosmos-platform
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: manual
    security.cosmos.ai/rotation-schedule: 90d
    security.cosmos.ai/last-rotated: "2024-01-01"
  annotations:
    security.cosmos.ai/encryption: aes256
    security.cosmos.ai/access-control: rbac
    security.cosmos.ai/audit-logging: enabled
type: Opaque
data:
  # Authentication token configuration
  VITE_AUTH_TOKEN_KEY: base64_encoded_token_key
  VITE_AUTH_TOKEN_EXPIRY_BUFFER: base64_encoded_expiry_buffer
  VITE_AUTH_TOKEN_ISSUER: base64_encoded_token_issuer
  VITE_AUTH_TOKEN_AUDIENCE: base64_encoded_token_audience
  VITE_AUTH_TOKEN_ALGORITHM: base64_encoded_token_algorithm
  
  # JWT and refresh token secrets
  VITE_JWT_SECRET: base64_encoded_jwt_secret
  VITE_AUTH_REFRESH_TOKEN_SECRET: base64_encoded_refresh_token_secret
  
  # API and rate limiting configuration
  VITE_API_KEY: base64_encoded_api_key
  VITE_API_RATE_LIMIT_KEY: base64_encoded_rate_limit_key
  
  # Multi-factor authentication
  VITE_AUTH_MFA_SECRET: base64_encoded_mfa_secret