# Kubernetes Service configuration for Cosmos WFM Platform web interface
# Version: v1
# Purpose: Expose web application deployment internally with security and monitoring

apiVersion: v1
kind: Service

metadata:
  name: cosmos-web
  namespace: cosmos
  
  # Standard Kubernetes labels for service identification and management
  labels:
    app.kubernetes.io/name: cosmos-web
    app.kubernetes.io/part-of: cosmos-platform
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kubernetes
  
  # Prometheus monitoring annotations for metrics collection
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"

spec:
  # Internal cluster IP for secure access
  type: ClusterIP
  
  # Port configuration for HTTP traffic
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  
  # Pod selector using standard Kubernetes labels
  selector:
    app.kubernetes.io/name: cosmos-web
    app.kubernetes.io/part-of: cosmos-platform
  
  # Session handling configuration
  sessionAffinity: None
  
  # Only expose pods that are ready
  publishNotReadyAddresses: false